version: '3.3'

services:
    postgres:
        image: postgres:14
        environment:
            - POSTGRES_DB=dolce_vita_db
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=crd-1-BDP
        ports:
            - 5432:5432
        volumes:
            - ./postgres_data:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@mail.com
            - PGADMIN_DEFAULT_PASSWORD=root
        ports:
            - 5050:80

    mysql:
        image: mysql:5
        environment:
            - MYSQL_DATABASE=dolce_vita_db
            - MYSQL_USER=root
            - MYSQL_ROOT_PASSWORD=crd-1-BDP
            - PORT:3306
        ports:
            - 3306:3306
        volumes:
            - ./mysql_data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - MYSQL_ROOT_PASSWORD=crd-1-BDP
            - PMA_HOST=mysql
        ports:
            - 8080:80
